language: node_js
node_js:
  - "8.9"
install:
  - apt-get install ruby-sass
  - wget https://github.com/gohugoio/hugo/releases/download/v0.35/hugo_0.35_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - make
after_success:
  - bash deploy.sh
