language: node_js
node_js:
  - "10.15.2"
install:
  - bundle install
  - wget https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - make
after_success:
  - bash deploy.sh
