language: node_js
node_js:
  - "8.9"
install:
  - bundle install
  - wget https://github.com/gohugoio/hugo/releases/download/v0.42/hugo_0.42_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - make
after_success:
  - bash deploy.sh
