baseURL = "http://fournilsipma.fr/"
languageCode = "fr-fr"
title = "Fournil Sipma"
staticDir = "dist/static"
publishDir = "dist/public"
DefaultContentLanguage = "fr"

[params]
email = "fournilsipma@gmail.com"
phone = "+33 6 27 20 30 72"
address = [ "16 rue des Sapins", "27620 Gasny" ]
